SageMaker 설정 번역 초안 완료.
fast-ai-kr/ko-translation pull request #11
Opened 2019-08-16 15:54 UTC by deep-diver

테이블의 indentation 이 불가하여, 들여쓰기가 안된채로 놔두었습니다. 괜찮은 방법이 있다면, 알려주시면 감사하겠습니다.

2019-08-16 16:24 UTC, kkweon requested changes

2019-08-16 16:24 UTC, kkweon commented on fastai-env/sagemaker.md
> +![스택 생성](https://course.fast.ai/images/sagemaker/create_stack.png)
```suggestion

![스택 생성](https://course.fast.ai/images/sagemaker/create_stack.png)
```

2019-08-16 16:24 UTC, kkweon commented on fastai-env/sagemaker.md
> +![스택 생성 완료](https://course.fast.ai/images/sagemaker/01.png)
```suggestion

![스택 생성 완료](https://course.fast.ai/images/sagemaker/01.png)
```

2019-08-16 16:24 UTC, kkweon commented on fastai-env/sagemaker.md
> +![노트북 인스턴스 메뉴](https://course.fast.ai/images/sagemaker/17.png)
```suggestion

![노트북 인스턴스 메뉴](https://course.fast.ai/images/sagemaker/17.png)
```

2019-08-16 16:24 UTC, kkweon commented on fastai-env/sagemaker.md
> +![Stop 버튼](https://course.fast.ai/images/sagemaker/23.png)
```suggestion

![Stop 버튼](https://course.fast.ai/images/sagemaker/23.png)
```

2019-08-16 16:24 UTC, kkweon commented on fastai-env/update_kaggle.md
> +# Kaggle 커널로 작업 재개하기
이 파일 여기 들어오면 안되는 것 같아요 삭제해주세요.

2019-08-16 16:33 UTC, deep-diver commented on fastai-env/update_kaggle.md
> +# Kaggle 커널로 작업 재개하기
같이 끼어 들어왔네요;; 삭제하였습니다.

2019-08-16 16:38 UTC, deep-diver commented on fastai-env/sagemaker.md
> +![노트북 인스턴스 메뉴](https://course.fast.ai/images/sagemaker/17.png)
한줄 띄워서 이미지를 삽입하려고 하였으나, 
bullet point 에 대한 들여쓰기가 맞춰지지 않게 되어서 바로 아랫줄에 이미지 삽입을 하였습니다.

그런데 이미지의 크기가 작은경우 글자와 어우러져 버리는군요; 일단은 일괄 한줄 띄워쓰기를 적용하겠습니다.

2019-08-16 16:55 UTC, kkweon commented on fastai-env/sagemaker.md
> +![스택 생성](https://course.fast.ai/images/sagemaker/create_stack.png)
그런 경우라면 HTML을 사용하면 되긴 하는데 이건 찬성님에게 맡기겠습니다.

```suggestion
<p align="center">
  <img width="80%" src="https://course.fast.ai/images/sagemaker/create_stack.png" alt="스택 생성">
</p>
```

2019-08-16 17:19 UTC, deep-diver commented on fastai-env/sagemaker.md
> +![스택 생성](https://course.fast.ai/images/sagemaker/create_stack.png)
음.. 마크다운에는 HTML 태그를 최대한 피하고 싶어서, 이 부분은 일단 스킵 하도록 하겠습니당

2019-08-16 17:37 UTC, jehyunlee requested changes
>L68 : 문제 트러블슈팅 하기 -> 트러블슈팅 or 문제 해결하기

2019-08-16 18:06 UTC, deep-diver commented
@jehyunlee 반영되었습니다 :)

2019-08-17 01:14 UTC, deep-diver commented
이 이상의 수정에 대한 제안이 없으므로 Merge 하도록 하겠습니다. @jehyunlee @taegon @kkweon 님 감사합니다.

2019-08-17 01:14 UTC, merged