Deploying on Google App Engine  번역
fast-ai-kr/ko-translation pull request #26
Opened 2019-08-27 15:19 UTC by SeoEunkyo

검토 부탁 드립니다.

2019-08-27 18:53 UTC, kkweon requested changes
Good work. First pass review done.

2019-08-27 18:53 UTC, kkweon commented on fastai-env/Deploying on Google App Engine.md
> +-  [프로젝트 별 설정](#per-project_setup)
```suggestion
-  [프로젝트 설정](#per-project_setup)
```

i think it sounds more natural without the translation of `per`

2019-08-27 18:53 UTC, kkweon commented on fastai-env/Deploying on Google App Engine.md
> +## 프로젝트 별 설정<span id="per-project_setup"></span>
```suggestion
## 프로젝트 설정<span id="per-project_setup"></span>
```

2019-08-27 18:53 UTC, kkweon commented on fastai-env/Deploying on Google App Engine.md
> +**주의:**  다운로드 링크는 직접 파일이 다운로드를 시작해야합니다. 일반적으로 사용되는 뷰를 제공하는 공유링크와는 다른것 입니다.  필요시 아래의 주소에서 링크를 변경 할 수 있습니다.
This doesn't sound very natural. 
Especially,

> 다운로드 링크는 직접 파일이 다운로드를 시작해야합니다

Can you take a look again?

2019-08-27 18:53 UTC, kkweon commented on fastai-env/Deploying on Google App Engine.md
> +만약  배포 테스트만을 원한다면, Jeremy’s 곰 분류 모델이 기본적으로 설정 된 모델을 그래로 사용하면 됩니다.  모델의 가중치 URL은 이미 샘플 App에 기입 되어 있으므로 이 단계를 건너뛸 수 있습니다.
```suggestion
만약  배포 테스트만을 원한다면, Jeremy’s 곰 분류 모델이 기본적으로 설정 된 모델을 그[DAE]로 사용하면 됩니다. 모델의 가중치 URL은 이미 샘플 App에 기입 되어 있으므로 이 단계를 건너뛸 수 있습니다.
```

Typo

2019-08-27 18:53 UTC, kkweon commented on fastai-env/Deploying on Google App Engine.md
> +  app 폴더에 있는 ``server.py``를 편집기를 통하여 열고 ``model_file_url`` 이 부분을 위에서 복사 해둔 url로 변경해주세요.   같은 파일에서 ``classes = ['black', 'grizzly', 'teddys'] `` 에 부분 클래스 내용을 모델에서 예상하는 것으로 변경하세요.
```suggestion
  app 폴더에 있는 `server.py`를 편집기를 통하여 열고 `model_file_url` 이 부분을 위에서 복사 해둔 url로 변경해주세요.   같은 파일에서 `classes = ['black', 'grizzly', 'teddys'] ` 에 부분 클래스 내용을 모델에서 예상하는 것으로 변경하세요.
```

2019-08-27 18:53 UTC, kkweon commented on fastai-env/Deploying on Google App Engine.md
> +우선 Google Cloud 대쉬보드를 열어주세요, 그리고 **_Create Project_** 버튼을 클릭한 다음 새 GCP 프로젝트의 이름을 정해 줍니다.  새로운 비용청구를 위한 계정을 생성하거나 기존의 청구 계정을 이용 하여 설정 가능 합니다.  화면은 아래와 같을 것 입니다.
```suggestion
우선 Google Cloud 대쉬보드를 열어주세요, 그리고 **_Create Project_** 버튼을 클릭한 다음 새 GCP 프로젝트의 이름을 정해 줍니다. 새로운 비용청구를 위한 계정을 생성하거나 기존의 청구 계정을 이용 하여 설정 가능 합니다. 화면은 아래와 같을 것 입니다. 
```

2019-08-27 18:53 UTC, kkweon commented on fastai-env/Deploying_on_Google_App_Engine.md
> +﻿# Google App Engine에서 배포 하기
Please remove this file or the other.

2019-08-28 00:43 UTC, deep-diver commented on fastai-env/Deploying_on_Google_App_Engine.md
> +﻿# Google App Engine에서 배포 하기
I have removed this one

2019-08-28 06:20 UTC, deep-diver commented on fastai-env/Deploying on Google App Engine.md
> +**주의:**  다운로드 링크는 직접 파일이 다운로드를 시작해야합니다. 일반적으로 사용되는 뷰를 제공하는 공유링크와는 다른것 입니다.  필요시 아래의 주소에서 링크를 변경 할 수 있습니다.
@kkweon 

looks like he has made some changes, but it was not done through this in-line code editor.

2019-08-28 07:08 UTC, kkweon commented on fastai-env/Deploying on Google App Engine.md
> +## 프로젝트 별 설정<span id="per-project_setup"></span>
I still don't see the change.

2019-08-31 07:14 UTC, deep-diver commented
@kkweon all the required changes are applied, could you please check? Thank you

2019-08-31 14:56 UTC, kkweon approved these changes

2019-08-31 14:56 UTC, merged