Add : What You Need to Know Before Considering a PhD.md 초벌번역 완료
fast-ai-kr/ko-translation pull request #28
Opened 2019-08-30 08:31 UTC by MaliciousJ

What You Need to Know Before Considering a PhD.md 초벌번역 완료했습니다.

2019-08-30 19:18 UTC, kkweon requested changes
👍👍👍👍👍👍👍👍👍👍

2019-08-30 19:18 UTC, kkweon commented on fastai-etc/What You Need to Know Before Considering a PhD.md
> +>질문 : 저는 머신러닝에 관심이 있는 학부생입니다. 또한 저는 박사학위를 밣는데 있어 약간의 압박을 받고 있어요. 2년정도 업계에 종사하고 나서 다시 학교로 돌아가는 게 괜찮다고 생각하는지요?
```suggestion
>질문 : 저는 머신러닝에 관심이 있는 학부생입니다. 또한 저는 박사학위를 밟는데 있어 약간의 압박을 받고 있어요. 2년 정도 업계에 종사하고 나서 다시 학교로 돌아가는 게 괜찮다고 생각하는지요?
```

2019-08-30 19:18 UTC, kkweon commented on fastai-etc/What You Need to Know Before Considering a PhD.md
> +박사학위를 할지 말지를 둘러싼 대화는 종종 성공적으로 박사학위를 마친 사람에게 조언을 구하게 되는 선택편향으로 어려움을 겪습니다. 반면, 박사학위 없이 매혹적이고 최첨단의 일을 하는 많은 사람들은 이러한 주제의 질문을 받을 가능성이 적습니다. 대학원생 사이에서 불균형적으로 높은 우울증이나 박사과정에서의 기회비용과 같은 다른 중요한 요소들은 거의 논의되지
```suggestion
박사학위를 할지 말지를 둘러싼 대화는 종종 성공적으로 박사학위를 마친 사람에게 조언을 구하게 되는 선택편향으로 어려움을 겪습니다. 반면, 박사학위 없이 매혹적이고 최첨단의 일을 하는 많은 사람은 이러한 주제의 질문을 받을 가능성이 작습니다. 대학원생 사이에서 불균형적으로 높은 우울증이나 박사과정에서의 기회비용과 같은 다른 중요한 요소들은 거의 논의되지 않습니다. 수학 박사학위를 가진 사람으로서, 저는 다른 중요한 기술들을 소홀히 하면서, 좁은 분야에 너무 많은 시간을 보낸 것을 후회하고 있습니다. 일단 제가 현업에 참여하게 되었을 때, 많은 중요한 기술과 경험을 따라잡는 것처럼 느꼈습니다.
```

2019-08-30 19:18 UTC, kkweon commented on fastai-etc/What You Need to Know Before Considering a PhD.md
> +제가 [여기](http://www.fast.ai/2016/10/08/teaching-philosophy/)에 써놨듯이, 저는 문제를 해결하는 방법을 배움으로써 제 학부시절의 학문적 성공은 빈약한 것이였다는 것을 나중에야 깨닫게 되었습니다. 그러나 문제를 해결하는 방법이라는게 자기 스스로 어떻게 흥미로운 문제를 찾아내고 살펴볼 수 있는 지에 대한 방법은 아
```suggestion
제가 [여기](http://www.fast.ai/2016/10/08/teaching-philosophy/)에 써놨듯이, 저는 문제를 해결하는 방법을 배움으로써 제 학부 시절의 학문적 성공은 빈약한 것이었다는 것을 나중에야 깨닫게 되었습니다. 그러나 문제를 해결하는 방법이라는 게 자기 스스로 어떻게 흥미로운 문제를 찾아내고 살펴볼 수 있는지에 대한 방법은 아닙니다. 제 생각에는 **많은 상위권 학생들(내 예전 모습을 포함해서)은 박사가 되는 것은 "안전한" 선택이라고 생각합니다. 박사학위는 일류라고 여겨지는 일을 하려는 명확한 길이기 때문입니다.** 그러나 이러한 생각은 개인적으로 필요한 마일스톤들을 지연시키는 길이 될 수 있습니다.
```

2019-08-30 19:18 UTC, kkweon commented on fastai-etc/What You Need to Know Before Considering a PhD.md
> +구조화된 학교시스템과는 별개로 자신의 목표를 정의하고 설정하는 것을 배우거나, 자신의 고유한 동기부여와 가치를 깊게 연결시키는 것들을 말이죠.
```suggestion
구조화된 학교 시스템과는 별개로 자신의 목표를 정의하고 설정하는 것을 배우거나, 자신의 고유한 동기부여와 가치를 깊게 연결하는 것들을 말이죠.
```

2019-08-30 19:18 UTC, kkweon commented on fastai-etc/What You Need to Know Before Considering a PhD.md
> +심화된 수업을 듣거나, 논문을 읽거나, 실험을 설계하거나, 정기적으로 발표를 하거나, 제 분야에서 두 개의 컨퍼런스를 만들고, 학생이 경영하는 대학원 과정을 만들기도 했으며, 제 분야에서 선출된 졸업생 대표로서 일하기도 했고, 논문을 작성하기도 했습니다. 지나고 보니, 이 모든 기술들은 내가 깨달은 것보다 더 좁은 범위의 일부였고, 이 기술들 중 많은 것
```suggestion
심화 수업을 듣거나, 논문을 읽거나, 실험을 설계하거나, 정기적으로 발표를 하거나, 제 분야에서 두 개의 콘퍼런스를 만들고, 학생이 경영하는 대학원 과정을 만들기도 했으며, 제 분야에서 선출된 졸업생 대표로서 일하기도 했고, 논문을 작성하기도 했습니다. 지나고 보니, 이 모든 기술은 내가 깨달은 것보다 더 좁은 범위의 일부였고, 이 기술 중 많은 것들은 내가 기대했던 것보다 범용적이지 않았습니다. 예를 들어 학계에서의 글쓰기는 내가 블로그에 글(더 많은 대중에게 도달하는)을 작성하는 것과는 매우 달랐으며, 학계에서의 정치는 구조와 인센티브로 일어나는 스타트업의 정치와는 딴판이었습니다.
```

2019-08-30 19:18 UTC, kkweon commented on fastai-etc/What You Need to Know Before Considering a PhD.md
> +제가 박사과정을 마치고 첫번째 정규직 업무를 하게되었을 때가 27살이었습니다.(저는 다양한 연구와 장학금으로 대학원에서 학비를 벌고 있었지만 풀타임과는 달랐습니다.) 저는 현장에서 일하는 것과 제 실제 기술에 심각한 차이있다는 것을 배웠습니다. 저는 2년 간 고등학교에서 C++을 배웠고, 컴퓨터를 부전공했으며, 수학분야 박사과정 중에서 몇몇의 프로그래밍
```suggestion
제가 박사과정을 마치고 첫 번째 정규직 업무를 하게 되었을 때가 27살이었습니다(저는 다양한 연구와 장학금으로 대학원에서 학비를 벌고 있었지만 풀타임과는 달랐습니다). 저는 현장에서 일하는 것과 제 실제 기술에 심각한 차이가 있다는 것을 배웠습니다. 저는 2년간 고등학교에서 C++을 배웠고, 컴퓨터를 부전공했으며, 수학 분야 박사과정 중에서 몇몇 프로그래밍 프로젝트를 진행했음에도 불구하고, 컴퓨터 과학의 이론적인 부분에 초점을 맞췄고 많은 실용적인 컴퓨터 기술들이 부족했습니다. 이와는 대조적으로 내 fast.ai 공동창립자 Jeremy Howard는 18살에 맥킨지(McKinsey)의 컨설턴트로 첫 정규직을 시작했습니다. 그리고 제가 처음 직장에 들어가던 나이에 Jeremy는 정규직으로 거의 10년간을 일해왔으며, 여전히 운영되고 있는 2개의 스타트업을 세웠습니다. 대신에 저는 제가 박사과정을 하는 동안 기술 분야에서 다른 많은 것들을 배울 수 있었습니다.
```

2019-08-30 19:18 UTC, kkweon commented on fastai-etc/What You Need to Know Before Considering a PhD.md
> +분명히 말하자면, 인생은 경주가 아닙니다. 여러분은 기술분야로 전환할 수 있고 몇 살이든 새로운 기술을 배울 수 있습니다. 기술산업은  고령화가 심각하며, 젊은 창립자들에 대한 찬양은 해로운 미신에 가깝습니다. 그러나 저는 제가 20대 초반에 가졌던 열정들을 다시는 반복할 수 없을 것입니다.(건강하게 먹거나, 무거운 역기를 들고 수면의 우선순위를 따지는
```suggestion
분명히 말하자면, 인생은 경주가 아닙니다. 여러분은 기술 분야로 전환할 수 있고 몇 살이든 새로운 기술을 배울 수 있습니다. 기술산업은  고령화가 심각하며, 젊은 창립자들에 대한 찬양은 해로운 미신에 가깝습니다. 그러나 저는 제가 20대 초반에 가졌던 열정들을 다시는 반복할 수 없을 것입니다(건강하게 먹거나, 무거운 역기를 들고 수면의 우선순위를 따지는 것이지만 마음만은 같지 않습니다). 그리고 좁은 분야에 지나치게 집중해서 다른 많은 기술을 소홀히 하면서 그 시간을 비참하게 보낸 것을 후회합니다.
```

2019-08-30 19:18 UTC, kkweon commented on fastai-etc/What You Need to Know Before Considering a PhD.md
> +방금 막 떠오른 생각으로는, 박사학위가 없으면서도 흥미로운 최첨단 딥러닝 업무를 하는 다음과 같은 사람들이 떠오르네요.(이 목록은 완전한게 아니며, 수 많은 사람들이 더 있습니다.)
```suggestion
방금 막 떠오른 생각으로는, 박사학위가 없으면서도 흥미로운 최첨단 딥러닝 업무를 하는 다음과 같은 사람들이 떠오르네요(이 목록은 완전한 게 아니며, 수많은 사람이 더 있습니다).
```

2019-08-30 19:18 UTC, kkweon commented on fastai-etc/What You Need to Know Before Considering a PhD.md
> +- [Jeremy Howard](http://www.fast.ai/about/#jeremy) : fast.ai의 공동창립자, Enlitic의 창립자(의약품에 딥러닝을 적용한 첫번째 스타트업), 전(前) 랭킹 1위 캐글러, 캐글러 대표, fastmail과 Optimal Decisions Group의 창립자
```suggestion
- [Jeremy Howard](http://www.fast.ai/about/#jeremy) : fast.ai의 공동창립자, Enlitic의 창립자(의약품에 딥러닝을 적용한 첫번째 스타트업), 전(前) 랭킹 1위 캐글러, 캐글러 대표, fastmail(맞나요?)과 Optimal Decisions Group의 창립자
```

2019-08-30 19:31 UTC, MaliciousJ commented
주말에도 고생하십니다 ㅠㅠ
빠른 리뷰 감사드립니다.
반영했습니다!

2019-08-31 07:18 UTC, deep-diver requested changes

2019-08-31 07:18 UTC, deep-diver commented on fastai-etc/What You Need to Know Before Considering a PhD.md
> +- [Chris Olah](http://colah.github.io/) : distill.pub(?????)의 공동편집자, Google Brain의 연구원(대학 학위 없음)
```suggestion
- [Chris Olah](http://colah.github.io/) : distill.pub의 공동 편집자, Google Brain의 연구원(대학 학위 없음)
```

distill.pub 맞습니다

2019-08-31 07:18 UTC, deep-diver commented on fastai-etc/What You Need to Know Before Considering a PhD.md
> +- [Jeremy Howard](http://www.fast.ai/about/#jeremy) : fast.ai의 공동창립자, Enlitic의 창립자(의약품에 딥러닝을 적용한 첫번째 스타트업), 전(前) 랭킹 1위 캐글러, 캐글러 대표, fastmail(맞나요?)과 Optimal Decisions Group의 창립자
```suggestion
- [Jeremy Howard](http://www.fast.ai/about/#jeremy) : fast.ai의 공동 창립자, Enlitic의 창립자(의약품에 딥러닝을 적용한 첫 번째 스타트업), 전(前) 랭킹 1위 캐글러, 캐글 대표, fastmail과 Optimal Decisions Group의 창립자
```

fastmail 도 맞습니다

2019-08-31 10:24 UTC, deep-diver submitted a review, later dismissed

2019-08-31 14:56 UTC, kkweon submitted a review, later dismissed

2019-08-31 15:01 UTC, kkweon commented
고생많으셨습니다.

Tip. **Add suggestion to batch** 버튼으로 해주시면 커밋이 여러번 되지 않습니다.
![image](https://user-images.githubusercontent.com/2981167/64065697-7432e880-cbc5-11e9-9272-a26809dc1606.png)

2019-09-01 04:15 UTC, MaliciousJ commented
감사합니다 고생하셨습니다.

2019-09-01 05:00 UTC, kkweon approved these changes

2019-09-01 05:00 UTC, merged